### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by martoio** [Greenka236/Tea_cozy#1]
Best-practice tip: always use lowercase for your directory/file/ID/class names. That way you won't have to think about whether a name was capitalized or not, hence, less opportunities to make typos. It's also an established industry practice to keep everything lowercase and use either _ or - instead of spaces

https://github.com/Greenka236/Tea_cozy/blob/2124fce2281fa4b900aaa022ac30996e6630ee4d/index.html#L5

**Comment by Greenka236** [comment]
Thanks for the advice, will do it that way from now on.
